### ISSUE TITLE
libimobiledevice tools outdated

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/wptagent#262]
Hi Patrick,

we can't run the agent on raspberry pi with an actual iPad Air connected. The problem seems to be a changed UDID format for newer devices. There is [a fix](https://github.com/libimobiledevice/libimobiledevice/issues/701) in the `libimobiledevice` project but it's not in the compiled version in wptagent. 

Would you agree to update the libimobiledevice binaries and libs here? Otherwise we would add a flag to configure an alternative `ios_utils_path` and add newer libimobiledevice artifacts separately in our instances.

Regards, Nils

**Comment by pmeenan** [comment]
I'm flying back from London today so it will take a day or two but I'll
take care of it this week.

**Comment by nilskuhn** [comment]
Great!

**Comment by pmeenan** [comment]
Not sure it is going to be that easy. I have the binaries updated and can control the browser (and dev tools can communicate with tabs) but it looks like webkit's inspector may have changed pretty significantly for 12.2+ and the regular dev tools messages and classes don't seem to be working.

With any luck they just changed the mapping a bit but if they made radical changes to the events it is going to be a fair bit of work to get working

**Comment by pmeenan** [comment]
The tools have been updated and the agent has been fixed to work with iOS 12.2.

The best way (by far) to set up the agent on the Raspberry Pi is to use the [installation script](https://github.com/WPO-Foundation/wptagent-install#raspberry-pi-raspbian-stretch). It will build libimobiledevice from source and I just made a few tweaks so you can decide iOS, Android or Desktop testing at install time.

**Comment by nilskuhn** [comment]
Nice! Great, that you could fix this one so fast. We will test it asap and give you some feedback.

**Comment by nilskuhn** [comment]
Unfortunately it still doesn't work in our setup with the new iPad (with hyphen in UDID, iOS version 12.2) :(
I tried to connect via `ios_webkit_debut_proxy` manually:
```
$ ./ios_webkit_debug_proxy --version
ios_webkit_debug_proxy 1.8.4
Built with libimobiledevice v1.2.1, libplist v2.0.0

$ ./ios_webkit_debug_proxy -F -u 00008020-000924601111002E
No device found, is it plugged in?
Unable to attach 00008020-000924601111002E inspector
```
With an iPhone 7 it still works with your latest compiled libimobiledevice artifacts:
``` 
$ ./ios_webkit_debug_proxy --version                                     
ios_webkit_debug_proxy 1.8.4
Built with libimobiledevice v1.2.1, libplist v2.0.0

$ ./ios_webkit_debug_proxy -F -u c47306d267c51152901243c18da08f5924ee053d
Connected :9222 to iPhone (c47306d267c51152901243c18da08f5924ee053d)
```
When I run a test with wptagent the error log looks a bit different (see below). Here `ios_webkit_debug_proxy` binary seems to print usage instructions?!

Did you test it with an actual ios device (with hyphen in UDID)? And how did you compile the artifacts? With your [install script](https://github.com/WPO-Foundation/wptagent-install/blob/master/raspbian.sh)?

```
pi@colocation-iOS-2:~/wptagent/internal/support/ios/arm $ /usr/bin/python /home/pi/wptagent/wptagent.py --iOS --server https://<wptserver-url>/work/ --location iPadAir --shaper remote,192.168.1.6,21,321
/usr/lib/python2.7/dist-packages/urllib3/contrib/socks.py:31: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
  DependencyWarning
Python 2.7.9
Modern traceroute for Linux, version 2.0.20, Aug 16 2014
Copyright (c) 2008  Dmitry Butskoy,   License: GPL v2 or any later
Installing usbmuxd
/sbin/ldconfig.real: /usr/local/lib/libplist.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libplist++.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libios_webkit_debug_proxy.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libimobiledevice.so.6 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libusbmuxd.so.4 is not a symbolic link

Starting usbmuxd
No device found, is it plugged in?
00021: unlimited         0 ms burst 0 
q131093  50 sl. 0 flows (1 buckets) sched 65557 weight 0 lmax 0 pri 0 droptail
 sched 65557 type FIFO flags 0x0 0 buckets 0 active
Running agent, hit Ctrl+C to exit
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:840: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:840: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:840: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
Usage: ios_webkit_debug_proxy [OPTIONS]
iOS WebKit Remote Debugging Protocol Proxy v1.8.4.

By default, the proxy will list all attached iOS devices on:
  http://localhost:9221
and assign each device an incremented port number, e.g.:
  http://localhost:9222
which lists the device's pages and provides inspector access.

Your attached iOS device(s) must have the inspector enabled via:
  Settings > Safari > Advanced > Web Inspector = ON
and have one or more open browser pages.

To view the DevTools UI, either use the above links (which use the "frontend"
URL noted below) or use Chrome's built-in inspector, e.g.:
  chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1

OPTIONS:

  -u UDID[:minPort-[maxPort]]   Target a specific device by its digital ID.
        minPort defaults to 9222.  maxPort defaults to minPort.
        This is shorthand for the following "-c" option.

  -c, --config CSV      UDID-to-port(s) configuration.
        Defaults to:
          null:9221,:9222-9322
        which lists devices ("null:") on port 9221 and assigns
        all other devices (":") to the next unused port in the
        9222-9322 range, in the (somewhat random) order that the
        devices are detected.
        The value can be the path to a file in the above format.

  -f, --frontend URL    DevTools frontend UI path or URL.
        Defaults to:
          http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html
        Examples:
          * Use Chrome's built-in inspector:
              chrome-devtools://devtools/bundled/inspector.html
          * Use a local WebKit checkout:
              /usr/local/WebCore/inspector/front-end/inspector.html
          * Use an online copy of the inspector pages:
              http://chrome-devtools-frontend.appspot.com/static/33.0.1722.0/devtools.html
            where other online versions include:
              18.0.1025.74
              25.0.1364.169
              28.0.1501.0
              30.0.1599.92
              31.0.1651.0
              32.0.1689.3

  -F, --no-frontend     Disable the DevTools frontend.

  -s, --simulator-webinspector  Simulator web inspector socket
        address. Provided value value needs to be in format
        HOSTNAME:PORT or UNIX:PATH
        Defaults to:
          localhost:27753
        Examples:
          * TCP socket:
            192.168.0.20:27753
          * Unix domain socket:
            unix:/private/tmp/com.apple.launchd.2j5k1TMh6i/com.apple.webinspectord_sim.socket

  -d, --debug           Enable debug output.
  -h, --help            Print this usage information.
  -V, --version         Print version information and exit.
```

**Comment by pmeenan** [comment]
I tested it with an iOS 12.3 device but not specifically a device with a hyphen in the ID. I compiled the artifacts using the install script but [this script](https://github.com/WPO-Foundation/wptagent/blob/master/ios_install.sh) is also available and should build just the libimobiledevice bits..

What do you get when you run "ideviceinfo"? That will tell you if the underlying usbmuxd and libimobiledevice libraries are able to talk to the device.

FWIW, I couldn't get it to work well by upgrading an existing Jessie-based Raspbian image. Starting with a clean Raspbian Stretch did work though (I had to manually start usbmuxd using "sudo usbmuxd" though but the agent should also do that).

**Comment by nilskuhn** [comment]
We are running on rasbian jessie. So we will give it a try with a fresh stretch image asap and let you know whether it works for us. 

> What do you get when you run "ideviceinfo"? That will tell you if the underlying usbmuxd and libimobiledevice libraries are able to talk to the device.

How would I see whether they are able or not?

**Comment by pmeenan** [comment]
You'll either get info about the attached device or a "no devices connected" message :)

**Comment by nilskuhn** [comment]
I am getting information about the device, that works so far. That way I got UDID for testing the connection manually via `ios_webkit_debug_proxy` binary. But this binary doesn't seem to work properly with UDID of our iPad.

**Comment by pmeenan** [comment]
I'd say maybe try on Stretch to see if it helps but if the proxy still doesn't work then an [upstream issue](https://github.com/google/ios-webkit-debug-proxy/issues) to the proxy project is going to be the only way to get it fixed.

**Comment by nilskuhn** [comment]
Your compiled artifacts work on raspbian stretch with our actual iPad Air (with a hyphen in UDID). 
Thans again for your quick help!
